version: '3.3'
services:
  mongodb:
    image : mongo
    container_name: mongodb-hotels
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  hotels:
    container_name: hotels-container
    image: kushalgaur123/hotels:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: pnpm run start:prod
    env_file:
      - .env
    ports:
      - 3002:3002
      - 3004:3004
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge
